### ISSUE TITLE
Order of named group delimiters

### ISSUE THREAD

**Issue by a3nm** [remi-dupre/enum-spanner#5]
I'm trying out the named groups feature (because I wanted to add an example to the README ;)) but I got confused by the order in which the group delimiters are output:

```
$ echo ab | ./src/main.py '(?P<agroup>a*)(?P<bgroup>b*)'
0: ab[agroup⊣][bgroup⊣][⊢bgroup][⊢agroup]
1: a[agroup⊣][⊢bgroup][⊢agroup]b[bgroup⊣]
2: a[agroup⊣][bgroup⊣][⊢bgroup][⊢agroup]b
3: [⊢agroup]a[agroup⊣][⊢bgroup]b[bgroup⊣]
4: [⊢agroup]a[agroup⊣][bgroup⊣][⊢bgroup]b
5: [agroup⊣][bgroup⊣][⊢bgroup][⊢agroup]ab
```

In match 1 for instance, why are the delimiters in the order "close a", "open b", "open a"?

I guess this may just be a pretty-printing issue but ideally it should be displayed in a cleaner way to avoid confusion.

**Comment by remi-dupre** [comment]
It should be fixed for this example and more advanced ones:

```bash
$ echo ab | ./src/main.py '(?P<agroup>a*)(?P<bgroup>b*)'
0: ab[⊢bgroup][bgroup⊣][⊢agroup][agroup⊣]
1: a[⊢bgroup][⊢agroup][agroup⊣]b[bgroup⊣]
2: a[⊢bgroup][bgroup⊣][⊢agroup][agroup⊣]b
3: [⊢agroup]a[agroup⊣][⊢bgroup]b[bgroup⊣]
4: [⊢agroup]a[agroup⊣][⊢bgroup][bgroup⊣]b
5: [⊢bgroup][bgroup⊣][⊢agroup][agroup⊣]ab
```

**Comment by a3nm** [comment]
Hm arguably the order in output number 1 is still not very intuitive, because from the regexp you would expect the structure <a></a><b></b>, and we get <b><a></a></b>. I'm not completely sure that it can be formally defined but I'd expect the structure of the markers to always have the same structure as the capture groups in the regexp?
